### ISSUE TITLE
Codecov Implementation

### ISSUE THREAD

**Issue by aendeavor** [test-org-dm/docker-mailserver#3]
## Is your feature request related to a problem?

We should implement <https://codecov.io/> as an action too.

## Describe the solution you'd like

This should be an action that should run in parallel to `shellcheck` and `eclint`.

## Who will that feature be useful to?

This will give an overview over how good static code coverage with tests are. 

## What have you done already?

Seen the PR tomav#1708 where we talked about this. @williamdes could maybe help here?:)

**Comment by williamdes** [comment]
Hi
I am interested to make this work, once the coverage is generated the action can be implemented by a 3 lines copy pasta ;p

On what repository do I work ?
(See: https://github.com/tomav/docker-mailserver/issues/1699#issuecomment-741039298)

**Comment by aendeavor** [comment]
Nice! I would first like you to briefly read the last post from @wernerfred in #1, where he shows a diagram for how GH Actions are supposed to work in the future. This tests could run, as mentioned, next to `shellcheck`, `hadolint` and `eclint`.

> On what repository do I work ?

As the migration project is rather large, all changes related are done in this repository. You'll be able to work here exactly like on the main repo - I will make to rebase on tomav's master from time to time if this is easily possible.

**Comment by williamdes** [comment]
Hi !
I do not know if I should invest time into https://github.com/kward/shunit2 that make a release not a long time ago or bring https://github.com/SimonKagstrom/kcov support for the actual testing system

What do you think @aendeavor ?

**Comment by aendeavor** [comment]
A good question. @martin-schulze-vireso what do you think?

**Comment by martin-schulze-vireso** [comment]
I have not tried shunit. I am working towards getting coverage with bats but that might still be a long time away.

**Comment by williamdes** [comment]
Here is some examples with shunit, I loved how it was simple and felt like my phpunit experience
https://github.com/williamdes/sql-backup/blob/main/tests.sh

Bats seems unmaintained and code coverage is asked since 2018: https://github.com/bats-core/bats-file/issues/2

**Comment by martin-schulze-vireso** [comment]
> Bats seems unmaintained and code coverage is asked since 2018: bats-core/bats-file#2 

Yes, this has been a problem for a while now. There was a recent call for maintainers and volunteered and am working on improving the situation. Unfortunately, code coverage is not yet on the priority list and looks hard to fix right now.

**Comment by williamdes** [comment]
Oh okay, then I let you work on this task :)

**Comment by martin-schulze-vireso** [comment]
@williamdes As I said above: I won't be working on this for a while to come, since there are more pressing issues right now.

I'd be sad to see such a prolific project migrate away from bats but I can understand if you cannot wait for that. On the other hand, you are also free to contribute coverage testing for bats. ;)

**Comment by aendeavor** [comment]
Having read all of this, I too would like to see Bats being used in this project. As mentioned, Bats can use your help too @williamdes :)

**Comment by williamdes** [comment]
Looks like I said non sense because they too have an issue for coverage https://github.com/kward/shunit2/issues/135
My implementation of kcov https://github.com/kward/shunit2/issues/135#issuecomment-744745441 ontop of shunit could work here too

**Comment by williamdes** [comment]
Just randomly found that https://github.com/hacking-actions/bats-kcov

**Comment by aendeavor** [comment]
> Just randomly found that https://github.com/hacking-actions/bats-kcov

Is that actually usable, or can you make it usable for this use case?:)

**Comment by martin-schulze-vireso** [comment]
That one is relying on https://hub.docker.com/r/madhacking/bats-kcov which does not have its Dockerfile published.

**Comment by williamdes** [comment]
I think any implementation will not be very different from https://github.com/williamdes/sql-backup/blob/387810d62082a643009e227b945d72b7ebcde65a/.github/workflows/tests.yml#L69 or the one script line that this action does ^^ (https://github.com/hacking-actions/bats-kcov/blob/20a853d3133e38dbc7bde3532e3888acdfca773c/entrypoint.sh#L19)

**Comment by martin-schulze-vireso** [comment]
OKay, I just give kcov a short spin on bats-core's tests. Here are my results:

1. the problem described in the issue that I linked above seem to be resolved
2. bats-core's selftests are a bit special and fail, but that might not be an issue with this test suite, so you should give it a try

It really could be as simple as you described above. You just have to bear in mind, that there won't be any useful coverage information on the .bats files themselves, since they are preprocessed into a /tmp folder. However, they are probably of the least interest here.

**Comment by aendeavor** [comment]
When GH/actions ci in docker-mailserver/docker-mailserver#3 is merged, this issue can then be transferred there as well.

**Comment by aendeavor** [comment]
As docker-mailserver/docker-mailserver#6 is merged, this can be closed here. Please re-open there when an implementation is ready. If you decide to not do it anymore, that's also fine of course.
